<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'All Customers' => 'Visi klienti',
    'All Subscribers' => 'Visi abonementi',
    'If you want to subscribe click on submit.' => 'Klikšķini uz "Iesniegt", lai pierakstītos jaunumiem',
    'Join the newsletter' => 'Pierakstīties jaunumu saņemšanai',
    'Newsletter' => 'Jaunumu saņemšana',
    'Newsletter Customer' => 'Jaunumu saņemējklients',
    'Newsletter Customers' => 'Jaunumu saņemējklienti',
    'Newsletters' => 'Jaunumu saņemšana',
    'Subscribe Newsletter' => 'Pierakstīties jaunumu saņemšanai',
    'Thank you for subscribing to our newsletter' => 'Paldies, ka pierakstījies jaunumu saņemšanai',
    'Unsubscribe' => 'Atteikties',
    'Unsubscribe Newsletter' => 'Atteikties no turpmākās jaunumu saņemšanas',
    'You have already subscribed for the newsletter' => 'Tu jau pieteicies jaunumu saņemšanai',
    'You have been successfully removed from our subscriber list.' => 'Tu veiksmīgi tiki dzēsts/a no mūsu jaunumu saņēmēju saraksta',
];
