<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Applied to goods on which tax has to be applied' => '',
    'Based On' => '',
    'Flat' => '',
    'From Zip' => '',
    'From zip' => '',
    'From zip is required.' => '',
    'From zip should be less than to zip.' => '',
    'Is Zip Range' => '',
    'Manage Product Tax Classes' => '',
    'Manage Tax Rules' => '',
    'Manage Zones' => '',
    'Percent' => 'Procenti',
    'Product Tax Class' => '',
    'Product Tax Classes' => '',
    'Sales Tax' => 'Pārdošanas nodoklis',
    'Service Tax' => 'Servisa nodoklis',
    'Specific zones is required.' => '',
    'Tax' => 'PVN',
    'Tax Class' => '',
    'Tax Rule' => '',
    'Tax Rule Detail' => '',
    'Tax Rule Details' => '',
    'Tax Rules' => '',
    'Tax Zones' => '',
    'Taxes' => 'Nodokļi',
    'To zip' => '',
    'To zip is required.' => '',
    'Zip' => 'Pasta indekss',
    'Zone' => 'Zona',
    'Zones' => 'Zonas',
    'taxable goods' => 'Preces, kuram piemērojas nodoklis',
];
