<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add History' => 'Pievienot vēsturi',
    'Add Order History' => 'Pievienot Pirkumu vēsturi',
    'Add Payment' => 'Pievienot maksājumu',
    'Amount' => 'Summa',
    'Bill To' => 'Rēķina saņēmējs',
    'Cancelled' => 'Atcelts',
    'Cancelled Reversal' => 'Abpusēji atcelts',
    'Chargeback' => 'Naudas atgriešana',
    'Comments' => 'Komentāri',
    'Complete Order' => 'Pabeigt Pirkumu',
    'Completed' => 'Pabeigts',
    'Date Added' => 'Pievienošanas datums',
    'Denied' => 'Noraidīts',
    'Expired' => 'Noilgums',
    'Failed' => 'Neizdevies',
    'Incomplete Order' => 'Nepabeigts Pirkums',
    'Input Quantity should be >= minimum quantity' => 'Ievadītajam daudzumam ir jābūt lielākam par minimālo daudzumu vai vienādam ar to',
    'Invalid order' => 'Kļūdains Pirkums',
    'Invoice' => 'Rēķins',
    'Invoice ' => 'Rēķins',
    'Invoice Number:' => 'Rēķina numurs',
    'Invoices' => 'Rēķini',
    'Issue Date:' => 'Izdošanas datums',
    'Latest Orders' => 'Jaunākie Pirkumi',
    'Manage Orders' => 'Pārvaldīt Pirkumus',
    'My Orders' => 'Mani Pirkumi',
    'New Order Created' => 'Izveidots jauns Pirkums',
    'Order' => 'Pirkums',
    'Order Address' => 'Pirkuma adrese',
    'Order Completion' => 'Pirkums pabeigts',
    'Order Details' => 'Pirkuma detaļas',
    'Order History' => 'Pirkumu vēsture',
    'Order Id' => 'Pirkuma id',
    'Order Number:' => 'Pirkuma numurs',
    'Order Payment' => 'Pirkuma apmaksa',
    'Order Payment Transaction Map' => 'Pirkuma apmaksas transakciju karte',
    'Order Payments' => 'Pirkuma maksājumi',
    'Order Product' => 'Pirkuma preces',
    'Order Products' => 'Pirkuma preces',
    'Order could not be updated.' => 'Pirkumu nevarēja atjaunināt.',
    'Orders' => 'Pirkumi',
    'Paid amount can not be greater than the pending amount' => 'Apmaksātā summa nevar būt lielāka par gaidāmo summu',
    'Paid amount should be greater than 0' => 'Apmaksātajai summai ir jābūt lielākai par 0',
    'Payment Details' => 'Maksājuma detaļas',
    'Payment Method:' => 'Maksājuma veids:',
    'Payment Type' => 'Maksājuma tips',
    'Pending' => 'Gaida',
    'Please view your order under {section_link} section.' => 'Savu Pirkumu statusu un citas Pirkumu detaļas vari apskatīt sadaļā: {section_link}',
    'Previous' => 'Iepriekšējais',
    'Processed' => 'Apstrādāts',
    'Processing' => 'Apstrādā',
    'Product Details' => 'Preces detaļas',
    'Received Order' => 'Saņemts Pirkums',
    'Refunded' => 'Kompensēts',
    'Reversed' => 'Atgriezts',
    'Select Payment Method' => 'Izvēlies maksājuma veidu',
    'Ship To' => 'Piegādes adrese',
    'Shipped' => 'Piegādāts',
    'Shipping' => 'Piegade',
    'Shipping Address' => 'Piegādes adrese',
    'Status' => 'Pirkuma Statuss',
    'Terms' => 'Nosacījumi',
    'The transaction is saved successfully' => 'Transakcija ir veiksmīgi saglabāta',
    'Total Including Tax' => 'Kopējā summa ieskaitot nodokli',
    'Total Items' => 'Preces kopā',
    'Transaction Record' => 'Transakcijas ieraksts',
    'Unique Id' => 'Unikāls Id',
    'Update Order' => 'Atjaunināt Pirkumu',
    'View Cart' => 'Skatīt grozu',
    'View Invoice' => 'Skatīt rēķinu',
    'Voided' => 'Anulēts',
];
