<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add Payment' => 'Pievienot maksājumu',
    'Amount' => 'Summa',
    'Captured Amount' => 'Notvertā summa',
    'Cash Details' => 'Skaidras naudas detaļas',
    'Cash On Delivery' => 'Skaidrā naudā preci saņemot',
    'Cash On Delivery Settings' => 'Skaidra nauda preci saņemot iestatījumi',
    'Cash On Delivery Transaction' => 'Skaidra nauda preci saņemot transakcija',
    'Cash On Delivery Transactions' => 'Skaidra nauda preci saņemot transakcijas',
    'Default order status' => 'Pasūtījuma statuss pēc noklusējuma',
    'Manage Enhancements' => 'Pārvaldīt papildinājumus',
    'Manage Extensions' => 'Pārvaldīt paplašinājumus',
    'Manage Modifications' => 'Pārvaldīt modifikācijas',
    'Manage Modules' => 'Pārvaldīt moduļus',
    'Manage Payments' => 'Pārvaldīt maksājumus',
    'Order' => 'Pasūtījums',
    'Payment Method' => 'Apmaksas veids',
    'Payment Status' => 'Maksājuma statuss',
    'Payment Type' => 'Maksājuma tips',
    'Payments' => 'Maksājumi',
    'Paypal Settings' => 'Maksājuma iestatījumi',
    'Paypal Standard' => 'Maksājuma standarts',
    'Pending Amount' => 'Gaida summu',
    'Received Date' => 'Saņemšanas datums',
    'Select Payment Method' => 'Izvēlies maksājuma veidu',
    'Total Amount' => 'Kopējā summa',
    'Transaction Fee' => 'Transakcijas nodeva',
    'Transaction ID' => 'Transakcijas ID',
    'View Payments' => 'Skatīt maksājumus',
    'Bank Transfer' => 'Norēķināties ar karti vai pārskaitījumu',
    'Transaction Price' => 'Maksājuma komisija',
];
