<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'All Zones' => 'Visi apgabali',
    'Applicable Zones' => 'Piemērojamie apgabali',
    'Calculate Handling Fee' => 'Aprēķināt piegādes maksu',
    'Fixed' => 'Fiksēta',
    'Fixed plus handling' => 'Fiksēta + pasūtījuma apstrāde',
    'Flat Rate' => 'Vienotā likme',
    'Flat Rate Settings' => 'Vienotās likmes iestatījumi',
    'Flat shipping settings are saved successfully' => 'Vienotās likmes iestatījumi veiksmīgi saglabāti',
    'Free Shipping' => 'Bezmaksas piegāde',
    'Handling Fee' => 'Maksa par pasūtījuma apstrādi',
    'Manage Shipping' => 'Pārvaldīt piegādes',
    'Method Name' => 'Veida nosaukums',
    'No fees applied' => 'Netiek piemērota maksa ',
    'Per Item' => 'Par vienību',
    'Per Order' => 'Par pasūtījumu',
    'Percent' => 'Procenti',
    'Shipping' => 'Piegāde',
    'Shipping Comments' => 'Komentāri par piegādi',
    'Shipping Cost' => 'Piegāde',
    'Shipping Fee' => 'Piegādes maksa',
    'Shipping Fees' => 'Piegādes maksas',
    'Shipping Method' => 'Piegādes veids',
    'Specific Zones' => 'Īpašie apgabali',
    'In our Office' => 'Saņemšana mūsu ofisā',
    'Omniva Post Terminal' => '"Omniva" izņemšanas punkts',
    'DPD Delivery' => 'Piegāde uz adresi',
    'DPD Pickup' => '"DPD Pickup" izņemšanas punkts ("Pickup Paku Skapis" vai "Pickup Paku Bode")',
    'Latvijas Pasts Post Service' => 'Saņemšana "Latvijas Pasts" pasta nodaļā',
    'Circle K Station' => '"Circle K" degvielas uzpildes stacija',
    'Pasta Stacija' => '"Pasta Stacija" izņemšanas punkts',
];
