<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Alt Text' => 'Alt taga teksts',
    'Application environment whether development, stage or production' => 'Lietojumprogrammas vides veids: izstrādes vide, stage vide, produkcijas vide',
    'Description' => 'Apraksts',
    'Description for the site' => 'Vietnes apraksts',
    'Meta Description' => 'Meta tags: Apraksts',
    'Meta Keywords' => 'Meta tags: Atslēgvārdi',
    'Meta description for the site' => 'Meta tags: Vietnes apraksts',
    'Meta keywords for the site' => 'Meta tags: Vietnes atslēgvārdi',
    'Minimum 3 characters' => 'Minimālais garums ir 3 zīmes',
    'Name of the site' => 'Vietnes nosaukums',
    'Spaces not allowed. Allowed characters [a-zA-Z0-9_-]' => 'Atstarpes nav atļautas. Atļautās zīmes ir: [a-zA-Z0-9_-]',
];
