<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Delete failed due to error: <strong>{error}</strong>' => 'Dzēšana neizdevās dēļ sekojošās kļūdas: <strong>{error}</strong>',
    'Record has been saved successfully.' => 'Ieraksts tika veiksmīgi saglabāts.',
    'Record has been updated successfully.' => 'Ieraksts tika veiksmīgi atjaunināts.',
    'Thank you for contacting us. We would revert back to you within 24 hours.' => 'Paldies, ka sazinājāties ar mums! Centīsimies atbildēt 24 stundu laikā.',
    'There is an error sending email' => 'Nosūtot epastu radās kļūda',
];
