<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add To Cart' => 'Ielikt grozā',
    'Add to Cart' => 'Ielikt grozā',
    'Back' => 'Atpakaļ',
    'Billing Details' => 'Rēķina dati',
    'Checkout' => 'Noformēt pirkumu',
    'Confirm Order' => 'Apstiprināt pirkumu',
    'Continue Shopping' => 'Turpināt iepirkšanos',
    'Customer should agree to terms and conditions for the purchase' => 'Ir nepieciešams piekrist  piegādes, garantijas/atteikuma tiesību un privātuma nosacījumiem.',
    'Delivery Options' => 'Piegādes iespējas',
    'Edit Cart' => 'Mainīt groza saturu',
    'Incomplete Order' => 'Nepabeigts pirkums',
    'Input quantity should be >= 1' => 'Izvēlēto preču skaitam ir jābūt lielākam par vienu',
    'Input quantity should be >= minimum quantity' => 'Izvēlēto preču skaitam ir jābūt lielākam par minimālo skaitu, vai vienādam ar to',
    'Item' => 'Preces',
    'Payment Method' => 'Apmaksas veids',
    'Payment methods are not enabled. Please contact admin to enable payment methods.' => 'Apmaksas veidi nav iespējoti. Lūdzu sazinies ar administratoru, lai iespējotu apmaksas veidus',
    'Shipping methods are not enabled. Please contact admin to enable shipping methods.' => 'Piegādes veidi nav iespējoti. Lūdzu sazinies ar administratoru, lai iespējotu piegādes veidus',
    'Same As Billing Address' => 'Tāda pati, kā rēķina adrese',
    'Shopping Cart' => 'Pirkumu grozs',
    'Thank you for placing order with us. In case of any query, please contact us back' => 'Paldies par pirkumu! Ja Tev ir radušies kādi jautājumi, droši sazinies ar mums!',
    'The order is incomplete.' => 'Pirkums nav pabeigts.',
    'View Cart' => 'Skatīt grozu',
    'Your shopping cart is empty!' => 'Tavs pirkumu grozs ir tukšs!',
];
