<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Either products in the cart are not in stock or out of stock checkout is not allowed. Please contact system admin.' => 'Grozā esošie produkti vairs nav noliktavā,  vai arī šobrīd šo produktu pasūtīšana nav iespējama. Lūdzu sazinies ar mums, lai iegūtu vairak informācijas.',
    'The guest checkout is not allowed for the selected store.' => 'Izvēlētajā veikalā pasūtījuma noformēšana nav iespējama',
    'There should be atleast one item in the cart before you proceed for checkout.' => 'Lai noformētu pasūtījumu, pirkumu grozā ir jābūt vismaz 1 precei.',
];
