<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'About Us' => 'Par mums',
    'About us summary' => 'Par mums (apkopojums)',
    'Archived' => 'Arhivēts',
    'Contact Us' => 'Sazināties ar mums',
    'Content' => 'Saturs',
    'Delivery Information' => 'Apmaksa un piegāde',
    'Delivery information summary' => 'Piegādes informācijas apkopojums',
    'Information' => 'Informācija',
    'Manage Pages' => 'Pārvaldīt lapas',
    'Menu Item' => 'Izvēlnes sadaļa',
    'Page' => 'Lapa',
    'Pages' => 'Lapas',
    'Privacy Policy' => 'Privātuma nosacījumi',
    'Privacy policy summary' => 'Privātuma nosacījumu apkopojums',
    'Published' => 'Publicēts',
    'Summary' => 'Apkopojums',
    'Terms & Conditions' => 'Garantija un atteikuma tiesības',
    'Terms & condition summary' => 'Vispārīgo noteikumu apkopojums',
    'Trashed' => 'Dzēsts / Atkritumu grozā',
    'Unpublished' => 'Nav publicēts',
    'about us' => 'par mums',
    'about us description' => '"par mums" apraksts',
    'about-us' => 'par-mums',
    'deliverr information description' => 'piegādes informācijas apraksts',
    'delivery information' => 'piegādes informācija',
    'delivery-info' => 'precu-piegade',
    'privacy policy' => 'privātuma nosacījumi',
    'privacy policy description' => 'privātuma nosacījumu apraksts',
    'privacy-policy' => 'privātuma-nosacījumi',
    'terms' => 'precu-garantija-un-atteikuma-tiesibas',
    'terms & condition' => 'vispārīgie noteikumi',
    'terms & condition description' => 'vispārīgo noteikumu apraksts',
];
