<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'All Customers' => 'Visi klienti',
    'Billing Address' => 'Rēķina adrese',
    'Billing Receiver' => 'Rēķina saņēmējs',
    'Creating an account will make your shopping a nice experience. It would make your order management and tracking much friendly.' => 'Izveidojot kontu, iegūsti dažādas papildiespējas, lai padarītu iepirkšanos daudz ērtāku.',
    'Customer' => 'Klients',
    'Customer Activity' => 'Klienta aktivitāte',
    'Customer Group' => 'Klienta grupa',
    'Customer Groups' => 'Klienta grupas',
    'Customer Metadata' => 'Klienta metadati',
    'Customer Notified' => 'Klients tika informēts',
    'Customer Online' => 'Klients atrodas tiešsaistē',
    'Customer Service' => 'Klientu apkalpošana',
    'Customers' => 'Klienti',
    'Date Added' => 'Datums',
    'Default Address' => 'Adrese pēc noklusējuma',
    'Edit Profile' => 'Labot profilu',
    'Enter the e-mail address associated with your account. Click submit to have your information e-mailed to you.' => 'Ieraksti savā kontā uzdoto epasta adresi un klikšķini "Iesniegt", lai saņemtu tālākās instrukcijas.',
    'Forgot Password Request' => 'Aizmirstas paroles pieprasījums',
    'I am a returning customer' => 'Esmu klients / atgriežos kontā ',
    'Latest Customers' => 'Jaunākie klienti',
    'Manage Customer Groups' => 'Pārvaldīt klientu grupas',
    'Manage Customers' => 'Pārvaldīt klientus',
    'My Account' => 'Mans konts',
    'My Downloads' => 'Lejupielādes',
    'New Customer' => 'Jauns klients',
    'New Customer Registration' => 'Jauna klienta reģistrācija',
    'Notify Customer' => 'Informēt klientu',
    'Register Account' => 'Izveidot kontu',
    'Returning Customer' => 'Reģistrēts klients / atgriešanās',
    'Shipping Address' => 'Piegādes adrese',
    'Status' => 'Statuss',
    'added a new address.' => 'pievienota jauna adrese',
    'created a new order.' => 'izveidots jauns pasūtījums',
    'guest' => 'viesis',
    'logged in.' => 'pierakstījies',
    'registered for an account.' => 'reģistrējās kontam',
    'requested a new password.' => 'pieprasīja jaunu paroli',
    'updated their account details.' => 'atjaunināja konta detaļas',
    'updated their account password.' => 'atjaunināja konta paroli',
];
