<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'A random code for the product.' => 'Nejauši ģenerēts preces kods',
    'Alias for Product' => 'Preces aizstājējnosaukums',
    'Categories for the Product' => 'Preces kategorijas',
    'European Article Number' => 'Artikula numurs Eiropā',
    'Height for the product' => 'Produkta augstums',
    'If you want to emphasize the most important products, the Featured Products is exactly what you need.' => 'Noderīgs, ja vēlies izcelt vai ieteikt svarīgākās preces',
    'Initial stock for the product' => 'Preces sākotnējais atlikums noliktavā',
    'International Standard Book Number' => 'Grāmatas internacionālais standarta numurs',
    'Japanese Article Number' => 'Artikula numurs Japānā',
    'Length for the product' => 'Preces garums',
    'Manufacturer Part Number' => 'Preces ražotāja numurs',
    'Meta Description for Product' => 'SEO metatags Preces apraksts',
    'Meta Keywords for Product' => 'SEO metatags - Preces atslēgvārdi',
    'Minimum Quantity required to add product to the cart.' => 'Minimālais preču daudzums, lai to varētu ielikt grozā',
    'Model for Product' => 'Preces modelis',
    'Name for Product' => 'Preces nosaukums',
    'Price for Product' => 'Preces cena',
    'Price of the shipping' => 'Cena par piegādi',
    'Select "Out of Stock", "In Stock" as the message shown on the product page when the product quantity reaches 0.' => 'Parādīt "Nav noliktavā" paziņojumu, kad preču atlikums sasniedz 0',
    'Subtract Stock by the purchase quantity for e.g. If there are 100 laptops, and 2 items are purchased, stock would be reduced to 98.' => 'Automātiski amazināt pieejamo preču daudzumu noliktavā, piemēram, klientam nopērkot 2 no 100 datoriem, pircējam pieejamais preču daudzums samazināsies uz 98',
    'Tags associated with the product. e.g - Useful Products' => 'Produkta birkas (tagi), piemēram "Lietota prece", "Poplārs", utml.',
    'Universal Product Code' => 'Universālais preces kods',
    'Width for the product' => 'Preces platums',
];
