<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Memo' => 'Atmiņa',
    'Name' => 'Nosaukums',
    'Required By' => 'Nepieciešams no',
    'Result' => 'Rezultāts',
    'Scheduled maintenance is currently in progress. Please check back soon.' => 'Šobrīd notiek uzlabošanas darbi. Lūdzu, mēģini mazliet vēlāk.',
    'Services' => 'Servisi',
    'Site is temporarily unavailable.' => 'Diemžēl, šobrīd veikals īslaicīgi nav pieejams.',
    'System Configuration' => 'Sistēmas konfigurācija',
    'The application rebuild is in progress. Please wait.' => 'Lūdzu uzgaidi. Notiek sistēmas atjaunošana.',
    'The list of services provided below are at the system level so before running them, make sure they are not going to effect your current set up.' => 'Zemāk sarakstā pieejamie servisi darbojas sistēmas līmenī, tāpēc pirms to aktivizēšanas, lūdzu pārliecinies, vai tie neietekmēs tavus šī brīža uzstādījumus',
    'We apologize for any inconvenience.' => 'Atvainojamies par sagādātajām neērtībām.',
];
