<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Account' => 'Konts',
    'Activate' => 'Aktivizēt',
    'Address' => 'Adrese',
    'Address first line' => 'Faktiskā dzīvesvietas adrese',
    'Address second line' => 'Adreses papildus info',
    'Address1' => 'Iela un numurs vai mājas nosaukums',
    'Address2' => 'Papildus adrese',
    'Addresses' => 'Adreses',
    'CPanel Login' => 'Pierakstīšanās administrācijas panelī',
    'Change Others Password' => 'Mainīt kāda cita paroli',
    'Change Password' => 'Mainīt manu paroli',
    'Change Status' => 'Mainīt statusu',
    'Confirm Password' => 'Parole atkārtoti',
    'Confirm your email account' => 'Apstiprināt epastu',
    'Database Admin Password' => 'Datu bāzes administratora parole',
    'Database Admin User Name' => 'Datu bāzes administratora lietotājvārds',
    'Deactivate' => 'Deaktivizēt',
    'Edit Profile' => 'Labot profila informāciju',
    'Email' => 'Epasts',
    'Email Address' => 'Epasta adrese',
    'First Name' => 'Vārds',
    'Forgot Password' => 'Aizmirsi paroli?',
    'Forgot Password Request' => '',
    'Full Name' => 'Vārds un uzvārds',
    'Last Login' => 'Pēdējā pierakstīšanās',
    'Last Login IP' => 'Pēdējās pierakstīšanās IP',
    'Last Name' => 'Uzvārds',
    'Latest Users' => 'Jaunākie lietotāji',
    'Login' => 'Pierakstīties',
    'Logout' => 'Izrakstīties',
    'Manage Users' => 'Pārvaldīt lietotājus',
    'Mobile' => 'Tālruņa Numurs',
    'My Account' => 'Mans konts',
    'My Profile' => 'Mans profils',
    'Name' => 'Vārds',
    'New Password' => 'Jauna parole',
    'New User Registration' => 'Jauna lietotāja reģistrācija',
    'Notifications' => 'Notifikācijas',
    'Office Phone' => 'Ofisa tālrunis',
    'Owner' => 'Īpašnieks',
    'Password' => 'Parole',
    'Password token expiry' => 'Paroles token noilguma laiks',
    'Person' => 'Persona',
    'Person Details' => 'Personas dati',
    'Phone Number' => 'Telefona numurs',
    'Please confirm your email by clicking the link below to activate your account.' => '',
    'Postal Code' => 'Pasta indekss',
    'Profile' => 'Profils',
    'Profile Image' => 'Profila attēls',
    'Register' => 'Reģistrēties',
    'Related Id' => 'Saistītais Id',
    'Related Model' => 'Saistītais modelis',
    'Remember me' => 'Atcerēties mani',
    'Same As Billing Address' => 'Tāda pati,kā rēķina adrese',
    'Sign In' => 'Reģistrēties',
    'Status for the address i.e. if it is valid or not.' => 'Adreses pārbaudes statuss (ir pareiza vai nē)',
    'Super User Email' => 'Superlietotāja epasts',
    'Super User Password' => 'Superlietotāja parole',
    'Super Username' => 'Superlietotāja vārds',
    'The credentials passed are not valid.' => 'Lietotājvārds un/vai parole nav pareiza.',
    'Timezone' => 'Laika josla',
    'User' => 'Lietotājs',
    'User Settings' => 'Lietotāja iestatījumi',
    'Username' => 'Lietotājvārds',
    'Users' => 'Lietotāji',
    'You have changed your password' => 'Tava parole ir nomainīta.',
    'Your account is not active. Kindly contact system admin.' => 'Tavs konts nav aktivizēts. Ja esi tikko reģistrējies/usies, lūdzu pārbaudi epastu un veic konta aktivizēšanu, vai sazinies ar mums.',
    'Your email has been validated, Please login to continue.' => 'Tavs epasts tika veiksmīgi apstiprināts! Lūdzu, pieraksties, lai  turpinātu.',
    'Your email validation fails. Please contact system admin.' => 'Diemžēl, neizdevās apstiprināt epastu. Sazinies ar mums, lai paziņotu par kļūdu.',
];