<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Duration after which password token expire in seconds' => 'Paroles token noilgums sekundēs',
    'Letters, numbers & periods are allowed with a mail server name. eg test@yahoo.com' => 'Nosaukumā ir atļauti burti,cipari un @ zīme ar epasta domēnu (piemēram: mansvards@inbox.lv',
    'Minimum 3 characters. Spaces not allowed. Allowed characters [a-zA-Z0-9._]' => 'Minimālais garums ir 3 zīmes. Atļauti latīņu alfabēta mazie un lielie burti, skaitļi 0 līdz 9, punkts un apakšsvītra. Nedrīkst saturēt atstarpes.',
    'Must be of 6-20 characters. Contains atleast one special, one numeric & one alphabet.' => 'Jābūt 6-20 zīmju garumā, un ir jāsatur vismaz vienu speciālo simbolu, vienu skaitli un vienu alfabēta burtu.',
    'Must be of 6-20 characters. Contains atleast one special, one numeric & one alphabet. This is not applicable for super user.' => 'Jābūt 6-20 zīmju garumā, un ir jāsatur vismaz vienu speciālo simbolu, vienu skaitli un vienu alfabēta burtu.',
    'Super Administrator password' => 'Superadministratora parole',
    'Super User Name for the site' => 'Superlietotāja vārds vietnē',
    'Super administrator password for the database' => 'Superadministratora datu bāzes parole',
    'Super administrator username for the database' => 'Superadministratora  datu bāzes lietotājvārds',
];
