<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<div class="notifications">
                                                    <ul>
                                                        <li>Must contains one digit from 0-9</li>
                                                        <li>Must contains one alphabet(case insensitive)</li>
                                                        <li>Must contains one special symbol</li>
                                                        <li>Match anything with previous condition checking
                                                                {6,20} length at least 6 characters and maximum of 20</li>
                                                    </ul>
                                                </div>' => '',
    '<div class="notifications">
                                                    <ul>
                                                        <li>Must contains one digit from 0-9</li>
                                                        <li>Must contains one alphabet(case insensitive)</li>
                                                        <li>Must contains one special symbol</li>
                                                        <li>Match anything with previous condition checking
                                                                {6,20} length at least 6 characters and maximum of 20</li>
                                                    </ul>
                                                </div>' => '@@
                                                <div class="notifications">
                                                    <ul>
                                                        <li>Jāsatur vismaz vienu skaitli no 0 līdz 9</li>
                                                        <li>Jāsatur vismaz vienu lielo vai mazo alfabēta burtu</li>
                                                        <li>Jāsatur vismaz vienu speciālo simbolu</li>
                                                        <li>Jābūt 6 līdz 20 zīmju garai (atļauta jebkāda iepriekšminēto nosacījumu kombinācija)</li>
                                                        <li>Paroles piemērs: 1g%8W&</li>
                                                    </ul>
                                                </div>@@',
    'Password has been changed successfully.' => 'Parole tika veiksmīgi nomainīta.',
    'The given email is not registered with us. Please enter a valid email.' => 'Šāda epasta adrese netika atrasta mūsu sistēmā. Pārliecinies,ka ievadīji pareizu adresi,un sazinies ar mums, ja uzskati šo par kļūdu.',
    'User settings are saved successfully.' => 'Lietotāja iestatījumi tika veiksmīgi saglabāti.',
    'You have successfully registered with the system. An activation email has been sent at your registered email address.' => 'Reģistrācija ir veikta! Uz tevis norādīto epastu tika nosūtītas konta aktivizācijas instrukcijas, tāpēc pārbaudi to pēc brīža.
        Ja tomēr nesaņēmi paziņojumu (tai skaitā, pārliecinoties, vai ziņa nav nejauši piegādāta Mēstuļu (Spam) sadaļā), lūdzu sazinies ar mums, lai informētu par šo problēmu.',
    'Your account is not in active status.' => 'Tavs konts šobrīd ir neaktīvs',
    'Your login credentials are sent on registered email address.' => 'Konta dati tika nosūtīti uz tevis norādīto epastu, tāpēc pārbaudi to pēc brīža.
        Ja tomēr nesaņēmi paziņojumu (tai skaitā, pārliecinoties, vai ziņa nav nejauši piegādāta Mēstuļu (Spam) sadaļā), lūdzu sazinies ar mums, lai informētu par šo problēmu.',
];
