<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Action' => 'Darbība',
    'Add to Wish List' => 'Pievienot vēlmju sarakstam',
    'Already added to wishlist' => 'Jau atrodas vēlmju sarakstā',
    'My Wish List' => 'Mans vēlmju saraksts',
    'Wish List' => 'Vēlmju saraksts',
    'Wishlist' => 'Vēlmju saraksts',
    'Your wish list is empty!' => 'Tavs vēlmju saraksts šobrīd ir tukšs. Pievienot ikvienu preci vari, noklikšķinot uz tās apakšā vai sānos redzamās sirsniņas ikonas',
];
